version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "tms"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6: