spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test
  application:
    name: tms
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true