server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "test"
  jpa:
    hibernate:
      ddl-auto: update